package com.test.tcc.greendaodemo.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.test.tcc.greendaodemo.User;
import com.test.tcc.greendaodemo.User2;

import com.test.tcc.greendaodemo.greendao.UserDao;
import com.test.tcc.greendaodemo.greendao.User2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig user2DaoConfig;

    private final UserDao userDao;
    private final User2Dao user2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        user2DaoConfig = daoConfigMap.get(User2Dao.class).clone();
        user2DaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        user2Dao = new User2Dao(user2DaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(User2.class, user2Dao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        user2DaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public User2Dao getUser2Dao() {
        return user2Dao;
    }

}
